// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Tategumi.Mac
{
	public partial class SKCanvasView : NSView
	{
		public SKCanvasView (IntPtr handle) : base (handle)
		{
		}
	}
}
